old_sound_rabbit_mq:
    producers:
        job_shedule:
            connection:       default
            exchange_options: {name: 'job_queue', type: direct}
            queue_options:
                name: job_shedule
                arguments:
                    x-dead-letter-exchange: ['S', 'job_queue']
                    x-dead-letter-routing-key: ['S', 'job_queue']
                routing_keys:
                    - job_shedule

    consumers:
        job_shedule:
            connection:       default
            exchange_options: {name: 'job_queue', type: direct}
            queue_options:
                name: job_shedule
                arguments:
                    x-dead-letter-exchange: ['S', 'job_queue']
                    x-dead-letter-routing-key: ['S', 'job_queue']
                routing_keys:
                    - job_shedule
            callback: job_queue_manager
        job_queue:
            connection:       default
            exchange_options: {name: 'job_queue', type: direct}
            queue_options:
                name: 'job_queue'
                routing_keys:
                    - 'job_queue'
            callback: job_queue_manager